# Generated by Django 5.2.1 on 2025-06-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('teacher_age', models.IntegerField()),
                ('student_age', models.IntegerField()),
                ('teacher_email', models.EmailField(max_length=254)),
                ('student_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
