# Generated by Django 5.2.1 on 2025-06-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teacher_id', models.IntegerField(unique=True)),
                ('age', models.IntegerField()),
                ('total_subject', models.IntegerField()),
                ('standard', models.IntegerField()),
            ],
        ),
    ]
